import type { DenunciaModel } from '../types/Denuncia';

export const userMock = {
  id: 1,
  nome: 'Usuário Mock',
  cpf: '000.000.000-00',
  telefone: '000000000',
  email: 'mock@mock.com',
  senha: '',
  secretaria: {
    id: 1,
    nome: 'Secretaria Mock',
    sigla: 'SM',
  },
  perfil: {
    id: 1,
    nome: 'Cidadão',
  },
  criadoEm: new Date().toISOString(),
  criadoPor: null,
};

export const secretariasMock = [
  {
    id: 1,
    nome: 'Secretaria Municipal de Obras e Serviços Públicos',
    sigla: 'SEMOSP',
  },
  { id: 2, nome: 'Secretaria Municipal de Saúde', sigla: 'SEMUS' },
  { id: 3, nome: 'Secretaria Municipal de Educação', sigla: 'SEMED' },
  {
    id: 4,
    nome: 'Secretaria Municipal de Trânsito e Transportes',
    sigla: 'SMTT',
  },
  {
    id: 5,
    nome: 'Secretaria Municipal de Urbanismo e Habitação',
    sigla: 'SEMURH',
  },
  {
    id: 6,
    nome: 'Secretaria Municipal da Criança e Assistência Social',
    sigla: 'SEMCAS',
  },
  { id: 7, nome: 'Secretaria Municipal de Meio Ambiente', sigla: 'SEMMAM' },
  {
    id: 8,
    nome: 'Secretaria Municipal de Planejamento e Desenvolvimento',
    sigla: 'SEPLAN',
  },
  { id: 9, nome: 'Secretaria Municipal de Governo', sigla: 'SEMGOV' },
  {
    id: 10,
    nome: 'Secretaria Municipal de Segurança com Cidadania',
    sigla: 'SEMUSC',
  },
  {
    id: 11,
    nome: 'Secretaria Municipal de Agricultura, Pesca e Abastecimento',
    sigla: 'SEMAPA',
  },
  { id: 12, nome: 'Secretaria Municipal de Cultura', sigla: 'SECULT' },
  {
    id: 13,
    nome: 'Secretaria Municipal de Desportos e Lazer',
    sigla: 'SEMDEL',
  },
  { id: 14, nome: 'Secretaria Municipal da Fazenda', sigla: 'SEMFAZ' },
  { id: 15, nome: 'Secretaria Municipal de Turismo', sigla: 'SETUR' },
];

export const denunciasMock: DenunciaModel[] = [
  {
    id: 1,
    descricao: 'Poste com lâmpada queimada há mais de uma semana.',
    tipo: {
      id: 8,
      nome: 'Lampada queimada',
      categoria: { id: 2, nome: 'Infraestrutura', cor: '#333' },
    },
    files: [
      { id: 1, nome: 'poste_quebrado_1.jpg', tipo: 'imagem' },
      { id: 2, nome: 'poste_quebrado_2.jpg', tipo: 'imagem' },
      { id: 3, nome: 'poste_quebrado_3.jpg', tipo: 'imagem' },
      { id: 4, nome: 'poste_quebrado_4.jpg', tipo: 'imagem' },
      { id: 5, nome: 'poste_quebrado_5.mp4', tipo: 'video' },
    ],
    acao: null,
    bairro: "Ponta d'Areia",
    rua: 'Avenida Litorânea',
    pontoDeReferencia: 'Próximo ao quiosque Parada Obrigatória',
    longitude: -44.2929,
    latitude: -2.4921,
    criadaEm: new Date('2025-07-24T10:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 2,
    descricao: 'Lixo e entulho acumulado na calçada.',
    tipo: {
      id: 6,
      nome: 'Coleta de lixo',
      categoria: { id: 2, nome: 'Infraestrutura', cor: '#333' },
    },
    files: [{ id: 3, nome: 'lixo_acumulado.mp4', tipo: 'video' }],
    acao: null,
    bairro: 'Centro',
    rua: 'Rua do Giz',
    pontoDeReferencia: 'Em frente ao Museu Histórico',
    longitude: -44.3055,
    latitude: -2.5283,
    criadaEm: new Date('2025-07-21T14:30:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 3,
    descricao: 'Buraco de grande proporção no asfalto.',
    tipo: {
      id: 4,
      nome: 'Buraco na rua',
      categoria: { id: 2, nome: 'Infraestrutura', cor: '#333' },
    },
    files: [
      { id: 4, nome: 'buraco_rua.jpg', tipo: 'imagem' },
      { id: 5, nome: 'buraco_perigo.mp4', tipo: 'video' },
    ],
    acao: null,
    bairro: 'Renascença',
    rua: 'Avenida Colares Moreira',
    pontoDeReferencia: 'Perto do Tropical Shopping',
    longitude: -44.2825,
    latitude: -2.5089,
    criadaEm: new Date('2025-07-22T08:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 4,
    descricao: 'Árvore com galhos quebrados pendurados.',
    tipo: {
      id: 13,
      nome: 'Podar arvores',
      categoria: { id: 2, nome: 'Infraestrutura', cor: '#333' },
    },
    files: [{ id: 6, nome: 'arvore_perigo.jpg', tipo: 'imagem' }],
    acao: null,
    bairro: 'Jardim Renascença',
    rua: 'Rua das Palmeiras',
    pontoDeReferencia: 'Próximo à Praça da Criança',
    longitude: -44.28,
    latitude: -2.51,
    criadaEm: new Date('2025-07-22T15:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 5,
    descricao: 'Sinalização de trânsito apagada.',
    tipo: {
      id: 21,
      nome: 'Ma sinalizacao',
      categoria: { id: 5, nome: 'Trânsito e Transporte', cor: '#A1FF33' },
    },
    files: [{ id: 7, nome: 'sinalizacao_apagada.jpg', tipo: 'imagem' }],
    acao: null,
    bairro: 'São Francisco',
    rua: 'Avenida dos Holandeses',
    pontoDeReferencia: 'Perto do Farol da Barra',
    longitude: -44.295,
    latitude: -2.515,
    criadaEm: new Date('2025-07-23T09:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 6,
    descricao: 'Foco de água parada com risco de dengue.',
    tipo: {
      id: 19,
      nome: 'Foco de dengue',
      categoria: { id: 4, nome: 'Saúde Pública', cor: '#5733FF' },
    },
    files: [
      { id: 8, nome: 'agua_parada_1.jpg', tipo: 'imagem' },
      { id: 9, nome: 'agua_parada_2.jpg', tipo: 'imagem' },
    ],
    acao: null,
    bairro: 'Olho d’Água',
    rua: 'Rua da Saudade',
    pontoDeReferencia: 'Próximo ao Posto de Saúde',
    longitude: -44.3,
    latitude: -2.525,
    criadaEm: new Date('2025-07-23T11:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 7,
    descricao: 'Descarte ilegal de resíduos próximo a um rio.',
    tipo: {
      id: 15,
      nome: 'Descarte ilegal',
      categoria: { id: 3, nome: 'Meio Ambiente', cor: '#33FF57' },
    },
    files: [{ id: 10, nome: 'lixo_rio.mp4', tipo: 'video' }],
    acao: null,
    bairro: 'Calhau',
    rua: 'Avenida dos Caiacós',
    pontoDeReferencia: 'Perto da Praia do Calhau',
    longitude: -44.29,
    latitude: -2.5,
    criadaEm: new Date('2025-07-23T13:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 8,
    descricao: 'Acessibilidade irregular em calçada pública.',
    tipo: {
      id: 1,
      nome: 'Acessibilidade irregular',
      categoria: { id: 1, nome: 'Acessibilidade', cor: '#FF5733' },
    },
    files: [
      { id: 11, nome: 'calcada_irregular.jpg', tipo: 'imagem' },
      { id: 12, nome: 'acessibilidade_video.mp4', tipo: 'video' },
    ],
    acao: null,
    bairro: 'Turú',
    rua: 'Rua das Gaivotas',
    pontoDeReferencia: 'Próximo ao Mercado do Turú',
    longitude: -44.285,
    latitude: -2.52,
    criadaEm: new Date('2025-07-23T16:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 9,
    descricao: 'Semáforo quebrado causando transtornos.',
    tipo: {
      id: 22,
      nome: 'Semaforo quebrado',
      categoria: { id: 5, nome: 'Trânsito e Transporte', cor: '#A1FF33' },
    },
    files: [{ id: 13, nome: 'semaforo_quebrado.jpg', tipo: 'imagem' }],
    acao: null,
    bairro: 'Vinhais',
    rua: 'Avenida dos Africanos',
    pontoDeReferencia: 'Perto da Igreja de São José',
    longitude: -44.298,
    latitude: -2.53,
    criadaEm: new Date('2025-07-23T17:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
  {
    id: 10,
    descricao: 'Falta de medicamento essencial na UBS.',
    tipo: {
      id: 18,
      nome: 'Falta de medicamento',
      categoria: { id: 4, nome: 'Saúde Pública', cor: '#5733FF' },
    },
    files: [{ id: 14, nome: 'falta_medicamento.jpg', tipo: 'imagem' }],
    acao: null,
    bairro: 'Cohab',
    rua: 'Rua das Orquídeas',
    pontoDeReferencia: 'Próximo à UBS Cohab',
    longitude: -44.287,
    latitude: -2.505,
    criadaEm: new Date('2025-07-23T18:00:00Z').toISOString(),
    usuario: userMock,
    denunciaIndeferida: null,
  },
];
